version: '3'
volumes:
  bundle_cache:
services:
  rails_api:
    container_name: demoapi
    image: demoapi:1.0.0
    environment:
      - RAILS_ENV=development
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    #reference: https://docs.docker.com/compose/rails/
    volumes:
      - .:/demoapi
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - demoapinet
  postgres:
    image: postgres:11.2
    container_name: demoapi_postgres
    volumes:
      - ./data/db/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demoapi
      POSTGRES_PASSWORD: demoapi
      POSTGRES_DB: demoapi_development
    networks:
      - demoapinet

networks:
  demoapinet:

