default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: demoapi
  pool: 5

development:
  <<: *default
  database: demoapi_development

test:
  <<: *default
  database: demoapi_test
